baseURL = 'https://ppdiary.github.io/blog/'
languageCode = 'zh-tw'
title = '小紫鋼琴日記'
theme = "PaperMod"

# 必須要有這個結構，才能修復 rss.xml 的報錯
[author]
    name = "Purple"

# PaperMod 特有的參數設定
[params]
    env = "production"
    title = "小紫鋼琴日記"
    description = "這是我的第一個 Hugo 網站"
    author = "author"
    defaultTheme = "auto"
    showCodeCopyButtons = true
   

    listLayoutPages = true
    hideSummary = true      # 隱藏預覽文字
    showFullTextContent = false

    

    # 這裡可以暫時關閉 RSS，避免它一直報錯
    [params.homeInfoParams]
        Title = "Hello 你好 :)"
        Content = "新居落成，家徒四壁。"

# 強制 Hugo 使用新版的作者資訊格式
[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[[menu.main]]
    name = "近況"
    url = "/now/"
    weight = 10

 [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "標籤"
    url = "/tags/"
    weight = 30